export default {
  emailDuplicate: 0,
  nicknameDuplicate: 0,
  loginStatus: false,
  userInfo: {},
  otherInfo: {},
  userSchedule: [],
  activityPerDay: {},
  datePerDay: "",
  mateArticleList: {},
  mateArticleListTotalPage: 0,
  matePage: 0,
  changeList: {},
  // placeSearchInfo: null,
  placeSearchInfo: "",
  selectSportsCategory: "",
};
