export default {
  emailDuplicate: 0,
  nicknameDuplicate: 0,
  loginStatus: false,
  userInfo: {},
  otherInfo: {},
  profileUserSchedule: [],
  profileActivityPerDay: {},
  profileDatePerDay: "",
  profileMateListFromTotalPage: 0,
  profileMateListFrom: [],
  profileMateListToTotalPage: 0,
  profileMateListTo: [],
  mateArticleList: {},
  mateArticleListTotalPage: 0,
  mateArticleListTotalElements: 0,
  mateArticlePage: 0,
  changeList: {},
  placeSearchInfo: { page: 0 },
  selectSportsCategory: "",
  placeLike: "",
  addPlaceFilters: "",
  mapPosition: [],
  placeDetailInfo: "",
};
